### ISSUE TITLE
ValueError: mutable default <class 'woot.actions.Action'> for field create is not allowed: use default_factory

### ISSUE THREAD

**Issue by jrvidotti** [dearkafka/woot#2]
I am getting this error:

```
Traceback (most recent call last):
  File "/home/junior/.local/bin/woothook", line 5, in <module>
    from woothook.service import app
  File "/home/junior/.local/lib/python3.11/site-packages/woothook/service.py", line 4, in <module>
    from woot import AsyncChatwoot
  File "/home/junior/.local/lib/python3.11/site-packages/woot/__init__.py", line 1, in <module>
    from woot.api import Chatwoot, AsyncChatwoot
  File "/home/junior/.local/lib/python3.11/site-packages/woot/api.py", line 6, in <module>
    import woot.resources as wr
  File "/home/junior/.local/lib/python3.11/site-packages/woot/resources.py", line 22, in <module>
    import woot.actions as a
  File "/home/junior/.local/lib/python3.11/site-packages/woot/actions.py", line 23, in <module>
    @dataclass
     ^^^^^^^^^
  File "pydantic/dataclasses.py", line 231, in pydantic.dataclasses.dataclass
    repr_running = set()
  File "pydantic/dataclasses.py", line 207, in pydantic.dataclasses.dataclass.wrap
    _FIELD_INITVAR = _FIELD_BASE('_FIELD_INITVAR')
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'woot.actions.Action'> for field create is not allowed: use default_factory
```

```
$ pip freeze
anyio==4.2.0
certifi==2024.2.2
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
pydantic==1.10.13
python-slugify==8.0.4
python-status==1.0.1
sniffio==1.3.0
text-unidecode==1.3
typing_extensions==4.9.0
woot @ git+https://github.com/dearkafka/woot@6a0b777344a2cdccab3fdfc380b5d974d4607f3f

$ python --version
Python 3.11.4
```

**Comment by dearkafka** [comment]
yep, there is a change in behaviour in py3.11. the code works in 3.10. I will add support for 3.11 soon.

**Comment by dearkafka** [comment]
@vidz1979 seems fixed to me in main branch. feel free to re-open or create new issue.
